# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedembeds',
            old_name='provide_name',
            new_name='provider_name',
        ),
    ]
